#!/bin/zsh
# Check if boxes.tar exists and extract to ~/.vagrant.d/boxes/ if it does, download and extract it if it doesn't..
 
boxes_location=http://10.20.29.84:8081
echo $boxes_location
if [ -f "$HOME/Downloads/boxes.tar" ]; then
    mkdir -p $HOME/.vagrant.d/boxes && tar -C $HOME/.vagrant.d/boxes -xvzf $HOME/Downloads/boxes.tar
else
    if curl -o $HOME/Downloads/boxes.tar $boxes_location/boxes.tar; then
       tar -xvzf $HOME/Downloads/boxes.tar -C $HOME/.vagrant.d/boxes/
    else 
        exit 1 
    fi
fi

