---
- hosts: control
  strategy: free
  gather_facts: false
  become: true
  tasks:
  - name: Setting Hostname
    hostname:
      name: control.example.com
  - name: Creating automation User
    user:
      name: automation
      shell: /bin/bash
      groups: wheel
      append: yes
      password: $6$8OBbt3h8vmZHkCR5$80VffBqdwUHIgsegAGsB0Ecm1vLkTfvQ3IRzneGlb7BhyHbXU3U4ZzrdeTSmeI7DyKv4v6v5PF3wQcuSQ4EYG0
      update_password: on_create
  - name: Fixing Resolv File
    copy:
      content: nameserver 8.8.8.8
      dest: /etc/resolv.conf
  - name: Adding all addresses to hosts file.
    copy:
      content: |
        127.0.0.1    localhost.localdomain localhost
        ::1          localhost6.localdomain6 localhost6
        192.168.55.199 repo.example.com repo
        192.168.55.200 control.example.com control
        192.168.55.201 node1.example.com node1
        192.168.55.202 node2.example.com node2
        192.168.55.203 node3.example.com node3
        192.168.55.204 node4.example.com node4
        192.168.55.205 node5.example.com node5
      dest: /etc/hosts
  - name: Erasing Repos
    file:
      state: absent
      path: /etc/yum.repos.d/
  - name: Create repo directory
    file:
      state: directory 
      path: /etc/yum.repos.d/
  - name: Starting Firewalld
    service: 
      name: firewalld 
      enabled: yes
      state: started
  - name: Enabling Firewall Services
    firewalld:
      service: "{{ item }}"
      permanent: yes
      immediate: yes
      state: enabled
    loop:
      - http
      - https
  - name: Configuring network
#    nmcli:
#      type: ethernet
#      conn_name: 'System eth1'
#      ifname: eth1
#      ip4: 192.168.55.200/24
#      gw4: 192.168.55.1
#      dns4: 8.8.8.8
#      dns4_search: example.com
#      state: present
    shell: nmcli con mod "System eth1" ipv4.addresses 192.168.55.200/24 ipv4.gateway 192.168.55.1 ipv4.dns 8.8.8.8 ipv4.dns-search example.com ipv4.method manual
  - name: Reloaded Network.
    shell: nmcli con up "System eth1"
  - name: Generating RSA Key
    openssh_keypair:
      path: /home/automation/.ssh/id_rsa
      size: 2048
    become: yes
    become_user: automation
  - name: Disabling services
    selinux:
      state: disabled
  - name: Create SSHFS directory for post-playbooks
    file:
      path: /mnt/postplay
      state: directory
      mode: 0755
      owner: vagrant
      group: vagrant 
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
  - name: Create /etc/ansible directory
    file:
      path: /etc/ansible
      state: directory
  - name: Copy template to directory
    copy:
      src: playbooks/ansible.cfg.j2
      dest: /etc/ansible/ansible.cfg
  - name: Building Welcome Message
    blockinfile:
      dest: /etc/profile.d/welcome.sh
      block: |
        #!/bin/bash
        #
        echo -e '       
        #            _            _           _          _           _          _           _     
        #          /\ \          /\ \        /\ \     _ /\ \        /\ \       /\ \        _\ \   
        #         /  \ \        /  \ \      /  \ \   /\_\_\ \      /  \ \     /  \ \      /\__ \  
        #        / /\ \ \      / /\ \ \    / /\ \ \_/ / /\__ \    / /\ \ \   / /\ \ \    / /_ \_\ 
        #       / / /\ \ \    / / /\ \ \  / / /\ \___/ / /_ \ \  / / /\ \_\ / / /\ \ \  / / /\/_/ 
        #      / / /  \ \_\  / / /  \ \_\/ / /  \/____/ / /\ \ \/ / /_/ / // / /  \ \_\/ / /      
        #     / / /    \/_/ / / /   / / / / /    / / / / /  \/_/ / /__\/ // / /   / / / / /       
        #    / / /         / / /   / / / / /    / / / / /     / / /_____// / /   / / / / / ____   
        #   / / /________ / / /___/ / / / /    / / / / /     / / /\ \ \ / / /___/ / / /_/_/ ___/\ 
        #  / / /_________/ / /____\/ / / /    / / /_/ /     / / /  \ \ / / /____\/ /_______/\__\/ 
        #  \/____________\/_________/\/_/     \/_/\_\/      \/_/    \_\\/_________/\_______\/     
        '"#
        #
        # You are logged into \"`hostname`\" as user \"`whoami`\"
        # This system is running `cat /etc/redhat-release`
        # kernel is `uname -r`
        #
        #
        # Repo/AppStream 
        # Available to use from http://repo.example.com/BaseOS and http://repo.example.com/AppStream
        "
