---
- name: Add to known hosts and enable pw-less sudo
  hosts: nodes
  become: yes
  remote_user: automation
  become_user: automation
  tasks:

  - name: Create /home/automation/.ssh/
    file:
      path: /home/automation/.ssh
      state: directory
      mode: '0700'

  - name: Generate a key if not present
    openssh_keypair:
      path: /home/automation/.ssh/id_rsa
      size: 2048

  - name: Register public key of control
    command: cat /home/automation/.ssh/id_rsa.pub
    register: pub_key_control
    delegate_to: 127.0.0.1
    run_once: true

  - name: Distribute the public key on the nodes
    authorized_key:
      user: automation
      state: present
      key: "{{ pub_key_control.stdout }}"

  - name: Make sudo passwordless on all hosts for wheel group
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
    become: yes
    become_user: root
