---
- name: Add to known hosts and enable pw-less sudo
  hosts: nodes
  become: yes
  remote_user: automation
  become_user: automation
  tasks:

  - name: Create /home/automation/.ssh/ on the nodes
    file:
      path: /home/automation/.ssh
      state: directory
      mode: '0700'

  - name: Generate a key if not present on the nodes
    openssh_keypair:
      path: /home/automation/.ssh/id_rsa
      size: 2048

  - name: Register public key of control
    command: cat /home/automation/.ssh/id_rsa.pub
    register: pub_key_control
    delegate_to: 127.0.0.1
    run_once: true

  - name: Distribute the public key of control on the nodes
    authorized_key:
      user: automation
      state: present
      key: "{{ pub_key_control.stdout }}"

  - name: Make sudo passwordless on all nodes for the wheel group
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
    become: yes
    become_user: root
- name: Adding repos
  hosts: all
  become: yes 
  become_user: root
  tasks:
    - name: Adding repositories to all hosts
      yum_repository:
        name: BaseOS
        baseurl: http://repo.example.com/BaseOS
        description: BaseOS
    - name: Adding repositories to all hosts
      yum_repository:
        name: AppStream
        baseurl: http://repo.example.com/AppStream
        description: AppStream

# Prepare the machines for the partitioning task.
- name: Making volume groups on proxy
  hosts: proxy
  become: yes
  become_user: root
  tasks:
    - name: Make a primary partition on /dev/sdb
      parted:
        device: /dev/sdb
        number: 1
        state: present

- name: Making volume groups on webserver
  hosts: webservers:!node3
  become: yes
  become_user: root
  tasks:
    - name: Make a primary partition on /dev/sdb
      parted:
        device: /dev/sdb
        number: 1
        state: present
        flags: [ lvm ]
        part_end: 200MB
    - name: Make a volume group named research on /dev/sdb
      lvg:
        vg: research
        pvs: /dev/sdb1

- name: Making volume groups on database
  hosts: database
  become: yes
  become_user: root
  tasks:
    - name: Make a primary partition on /dev/sdb
      parted:
        device: /dev/sdb
        number: 1
        state: present
        flags: [ lvm ]
        part_end: 450MB
    - name: Make a volume group named research on /dev/sdb
      lvg:
        vg: research
        pvs: /dev/sdb1

- name: Making volume groups on development
  hosts: development
  become: yes
  tasks:
    - name: Make a primary partition on /dev/sdb
      parted:
        device: /dev/sdb
        number: 1
        flags: [ lvm ]
        state: present
