---
- name: Add to known hosts and enable pw-less sudo
  hosts: all:!repo
  become: no
  remote_user: automation
  tasks:
  - name: Generate a key if not present
    openssh_keypair:
      path: /home/automation/.ssh/id_rsa
      size: 2048

  - name: Register control public key
    shell: cat /home/automation/.ssh/id_rsa.pub
    register: pub_key
    delegate_to: control

  - name: Distribute the keys from control to nodes
    authorized_key:
      user: automation
      state: present
      key: "{{ item }}"
    with_file:
      - ~/.ssh/id_rsa.pub

  - debug:
      msg: "{{ ansible_hostname }},{{ ansible_eth1.ipv4.address }} {{ pub_key.stdout }}"

  - name: Remove known_hosts
    copy:
      path: /home/automation/.ssh/known_hosts
      content: ""

  - name: Add hosts to known_hosts
    known_hosts:
      state: present
      path: /home/automation/.ssh/known_hosts
      name: "{{ ansible_eth1.ipv4.address }}"
      key: "{{ ansible_hostname }},{{ ansible_eth1.ipv4.address }} {{ pub_key.stdout }}"

  - name: Make sudo passwordless on all hosts
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
    become: yes
    become_user: root
