---
- name: Generate key on nodes and set key auth for user automation
  hosts: nodes
  become: yes
  remote_user: automation
  become_user: automation
  tasks:
  - name: Create /home/automation/.ssh/ on the nodes
    file:
      path: /home/automation/.ssh
      state: directory
      mode: '0700'

  - name: Generate a key if not present on the nodes
    openssh_keypair:
      path: /home/automation/.ssh/id_rsa
      size: 2048

  - name: Register public key of control
    command: cat /home/automation/.ssh/id_rsa.pub
    register: pub_key_control
    delegate_to: 127.0.0.1
    run_once: true
    changed_when: false

  - name: Distribute the public key of control on the nodes
    authorized_key:
      user: automation
      state: present
      key: "{{ pub_key_control.stdout }}"

- name: Adding repos and make sudo passwordless
  hosts: all
  become: yes 
  become_user: root
  tasks:

  - name: Adding repositories to all hosts
    yum_repository:
      name: BaseOS
      baseurl: http://repo.example.com/BaseOS
      description: BaseOS
  - name: Adding repositories to all hosts
    yum_repository:
      name: AppStream
      baseurl: http://repo.example.com/AppStream
      description: AppStream

  - name: Make sudo passwordless on all nodes for the wheel group
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
    become: yes
    become_user: root

- name: Making volume group on webserver (200MB)
  hosts: webservers:!node3
  become: yes
  become_user: root
  tasks:
  - name: Make a volume group named research on /dev/sdb
    lvg:
      vg: research
      pvs: /dev/sdb
      
- name: Making volume group on database (500MB)
  hosts: database
  become: yes
  become_user: root
  tasks:
  - name: Make a volume group named research on /dev/sdb
    lvg:
      vg: research
      pvs: /dev/sdb

  - name: Welcome to the RHCE 8 Study/Test Environment!
    debug:
      msg:
        - 'Next Steps: Accessing The Systems:'
        - '- Control - 192.168.55.200'
        - '- Node 1 - 192.168.55.201'
        - '- Node 2 - 192.168.55.202'
        - '- Node 3 - 192.168.55.203'
        - '- Node 4 - 192.168.55.204'
        - '- Node 5 - 192.168.55.205'
        - '- Username/Password - automation/devops'
        - '--------------------------------------------------'
        - '- For root - use `sudo` or `sudo su`'
        - '- Access example - ssh automation@192.168.55.200'
        - '- Happy Studying!'

