---
- hosts: control
  become: true
  tasks: 
  - name: Sending Key to node1
    expect:
      command: ssh automation@node1.example.com 
      responses:
        'Are you sure you want to continue connecting': 'yes'
        'password': 'devops'
      timeout: 10
    become: yes
    become_user: automation
    ignore_errors: yes
  - name: Sending Key to node2
    expect:
      command: ssh automation@node2.example.com 
      responses:
        'Are you sure you want to continue connecting': 'yes'
        'password': 'devops'
      timeout: 10
    become: yes
    become_user: automation
    ignore_errors: yes
  - name: Sending Key to node3
    expect:
      command: ssh automation@node3.example.com 
      responses:
        'Are you sure you want to continue connecting': 'yes'
        'password': 'devops'
      timeout: 10
    become: yes
    become_user: automation
    ignore_errors: yes
  - name: Sending Key to node4
    expect:
      command: ssh automation@node4.example.com
      responses:
        'Are you sure you want to continue connecting': 'yes'
        'password': 'devops'
      timeout: 10
    become: yes
    become_user: automation
    ignore_errors: yes
  - name: Sending Key to node5
    expect:
      command: ssh automation@node5.example.com
      responses:
        'Are you sure you want to continue connecting': 'yes'
        'password': 'devops'
      timeout: 10
    become: yes
    become_user: automation
    ignore_errors: yes
