---
- hosts: node2
  strategy: free
  gather_facts: False
  become: true
  tasks:
  - name: Setting Hostname
    command: hostnamectl set-hostname node2.example.com
  - name: Creating Ansible User
    user:
      name: automation
      shell: /bin/bash
      groups: wheel
      append: yes
  - name: Changing User Password
    shell: echo devops | sudo passwd automation --stdin
  - name: Disabling services
    selinux:
      state: disabled
  - name: Adding all addresses to hosts file.
    copy:
      content: |
        127.0.0.1    localhost.localdomain localhost
        ::1          localhost6.localdomain6 localhost6
        192.168.56.199 repo.example.com repo
        192.168.56.200 control.example.com control
        192.168.56.201 node1.example.com node1
        192.168.56.202 node2.example.com node2
        192.168.56.203 node3.example.com node3
        192.168.56.204 node4.example.com node4
        192.168.56.205 node5.example.com node5
      dest: /etc/hosts

  - name: Erasing Repos
    shell: rm -rf /etc/yum.repos.d/*
  - name: Creating Temporary Repo File
    file:
      path: /etc/yum.repos.d/ipa.repo
      state: touch
      mode: 0755
  - name: Building Repo File
    blockinfile:
      dest: /etc/yum.repos.d/ipa.repo
      block: |
       [base]
       name=Base
       baseurl=http://repo/BaseOS
       gpgcheck=0
       enabled=1
       
       [apps]
       name=Apps
       baseurl=http://repo/AppStream
       gpgcheck=0
       enabled=1
    tags: repo
#  - name: Adding node4 address to hosts file
#    lineinfile:
#      path: /etc/hosts
#      line: 192.168.56.204 node4.example.com node4
#      create: yes
  - name: Configuring network
    command: nmcli con mod "System eth1" ipv4.addresses 192.168.56.202/24 ipv4.gateway 192.168.56.1 ipv4.method manual
  - name: Enabling IPV6
    shell: sysctl net.ipv6.conf.lo.disable_ipv6=0 ; sysctl net.ipv6.conf.all.disable_ipv6=0
  - name: Environment Packages Installed.
    shell: yum install -y man-pages 
  - name: Fixing Resolv File
    shell: echo 'nameserver 8.8.8.8' > /etc/resolv.conf
  - name: Enabling services
    service: name=firewalld enabled=true
  - name: Starting services
    service: name=firewalld state=started
    tags: repo
  - name: Erasing Repos
    shell: rm -rf /etc/yum.repos.d/*

...
