---
- hosts: repo
  strategy: free
  become: true
  gather_facts: false
  tasks:
  - name: Setting Hostname
    command: hostnamectl set-hostname repo.example.com
  - name: Configuring network
    shell: nmcli con mod "System eth1" ipv4.addresses 192.168.55.199/24 ipv4.gateway 192.168.55.1 ipv4.dns 8.8.8.8 ipv4.method manual
  - name: Adding all addresses to hosts file.
    copy:
      content: |
        127.0.0.1    localhost.localdomain localhost
        ::1          localhost6.localdomain6 localhost6
        192.168.55.199 repo.example.com repo
        192.168.55.200 control.example.com control
        192.168.55.201 node1.example.com node1
        192.168.55.202 node2.example.com node2
        192.168.55.203 node3.example.com node3
        192.168.55.204 node4.example.com node4
        192.168.55.205 node5.example.com node5
      dest: /etc/hosts
  
  - name: Enabling services
    shell: for i in httpd firewalld ; do systemctl enable $i;done
  - name: Starting services
    shell: for i in httpd firewalld ; do systemctl start $i;done
    ignore_errors: true
  - name: Starting Firewalld
    service: name=firewalld state=started
  - name: Enabling Firewall Services
    command: firewall-cmd --permanent --add-service=http --add-service=https --add-service=ntp --add-service=dns --add-service=kerberos --add-service=ldap --add-service=ldaps --add-service=ftp
  - name: Reloading Firewall
    command: firewall-cmd --reload
  - name: Enabling IPV6
    shell: sysctl net.ipv6.conf.lo.disable_ipv6=0 ; sysctl net.ipv6.conf.all.disable_ipv6=0
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
  - name: Fixing SELinux Contexts
    shell: restorecon -Rv /var/www/html
  - name: Building Welcome Message
    blockinfile:
      dest: /etc/profile.d/welcome.sh
      block: |
         #!/bin/bash
         #
         echo -e '
         Please do not reboot this node.
         You are logged into \"`hostname`\" as user \"`whoami`\"
         This system is running `cat /etc/redhat-release`
         kernel is `uname -r`
         '
...
